### ISSUE TITLE
How do I install and activate Mfractor on windows VS 2022

### ISSUE THREAD

**Issue by AustinJrMW** [matthewrdev/mfractor#1]
I was looking for a tool that would help me improve my debugging and row definition referencing. I discovered this tool but when I tried it through the extension manager, I was failing to utilise the trail version and I also wasn't able to understand how to install this legacy repo onto my machine to use mfractor.

Please could you assist with an explanation or breakdown of whether I can install it on VS 2022 on a windows machine and utilise the tool.

**Comment by matthewrdev** [comment]
Hi @AustinJrMW, thanks for reaching out.

I have provided some setup instructions for Visual Studio Mac but I'm unable to provide the same instructions for Visual Studio Windows. 

My new startup, Red-Point, is requiring all of my effort nowadays and unfortunately this means I can't do further maintenance on the product (hence why I retired and open sourced MFractor).

Thanks for the understanding :)
